added output and condition steps

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,18 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4.1.1
+
       - name: Run my own container action
         uses: ./
+        id: my-action
         with:
           who-to-greet: '@bhavish2'
+
+      - name: Output the answer
+        run: echo "The answer s ${{ steps.my-action.outputs.answer }}"
+
+      - name: Test the container
+        if: ${{ steps.my-action.outputs.answer != 42 }}
+        run: |
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
